# application log, default is info
log_level: info

# loads configuration to files
loads:
  - export: test.yml
    name: "v"
    dynamics:
      - consul:
          path: hellox/one
    # static configuration merged with other sources
    statics:
      - vault:
          path: hellox/one
          # default is empty
          path_prefix: secret
          # default is auth/approle/login, not need to set
          # app_role_base_path: auth/approle/login

# declare commands to run
services:
  # service name just for information purpose
  - name: cat my file
    # command will run inside of this path
    path: "."
    # command to run
    command: bash -c "cat test.yml; sleep 10; env; cat test.yml; sleep 10; cat test.yml"
    # environment variables to set
    # usable with gotemplate and sprig functions
    env:
      TEST: 1
      TEST2: 2
      HOSTTYPE: '{{ env "HOSTTYPE" }}'
    env_values:
    - "v/env"
    # filter of output, default is none
    filters_values:
    - "v/filters"
