# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: turna

git:
  ignore_tags:
    - docs

release:
  header: |
    Get the latest release with brew or binary:

    ```sh
    # curl -fSL https://github.com/rakunlabs/turna/releases/latest/download/turna_Linux_x86_64.tar.gz | tar -xz --overwrite -C ~/bin/ turna
    curl -fSL https://github.com/rakunlabs/turna/releases/download/{{ .Tag }}/turna_Linux_x86_64.tar.gz | tar -xz --overwrite -C ~/bin/ turna
    ```
  footer: |
    **Full Changelog**: https://github.com/rakunlabs/turna/compare/{{ .PreviousTag }}...{{ .Tag }}
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    main: ./cmd/turna
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    flags:
      - -trimpath
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

brews:
- name: turna
  homepage: https://github.com/rakunlabs/turna
  description: "swiss knife for services"
  repository:
    owner: brew-tools
    name: homebrew-tap
    token: "{{ .Env.BREW_TOKEN }}"
  folder: Formula

dockers:
- image_templates:
  - 'ghcr.io/rakunlabs/turna:{{ .Tag }}'
  - 'ghcr.io/rakunlabs/turna:{{ .Tag }}-alpine'
  - 'ghcr.io/rakunlabs/turna:{{ .Tag }}-alpine3.19.1'
  - 'ghcr.io/rakunlabs/turna:latest'
  dockerfile: ci/alpine.Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/rakunlabs/turna/main/README.md"
  - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Eray Ates\",\"email\":\"eates23@gmail.com\"}]"
  - "--label=io.artifacthub.package.license=MIT"
  - "--label=org.opencontainers.image.description=swiss knife for services"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--build-arg=ALPINE=alpine:3.19.1"
